apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-poller
  namespace: argocd-poller
  labels:
    app.kubernetes.io/name: github-actions-poller
---
# ServiceAccount no namespace argocd para obter token
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-poller
  namespace: argocd
  labels:
    app.kubernetes.io/name: github-actions-poller
