apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-kong-manager
  namespace: domestic
  labels:
    app: oauth2-proxy-kong-manager
spec:
  selector:
    app: oauth2-proxy-kong-manager
  ports:
    - name: http
      port: 4180
      targetPort: 4180
  type: ClusterIP
