apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: domestic
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30909
