apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: domestic
  labels:
    app: keycloak
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://postgres-keycloak:5432/domestic_keycloak"
  KC_HOSTNAME: "keycloak.domestic.local"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  JAVA_OPTS_APPEND: "-Xms128m -Xmx512m"
