apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: domestic-ingress
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: domestic
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: domestic
  source:
    repoURL: "https://github.com/Andersonfrfilho/domestic-kubernets"
    targetRevision: HEAD
    path: ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: domestic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Replace=false
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: batch
      kind: Job
      jsonPointers:
        - /spec/selector
        - /spec/template/metadata/labels
