apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: domestic
  labels:
    app: kong
spec:
  selector:
    app: kong
  type: NodePort
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30800
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 30801
    - name: manager
      port: 8002
      targetPort: 8002
      nodePort: 30802
