apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-db
  namespace: domestic
  labels:
    app: postgres
data:
  init.sql: |
    -- Create API user
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'backend_api') THEN
        CREATE ROLE backend_api WITH LOGIN PASSWORD 'backendapi123' CREATEDB;
      END IF;
    END
    $$;

    -- Create Cron user
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'backend_cron') THEN
        CREATE ROLE backend_cron WITH LOGIN PASSWORD 'backendcron123' CREATEDB;
      END IF;
    END
    $$;

    -- Grant privileges to API user
    GRANT CONNECT ON DATABASE domestic_postgres TO backend_api;
    GRANT CREATE ON DATABASE domestic_postgres TO backend_api;
    GRANT USAGE ON SCHEMA public TO backend_api;
    GRANT CREATE ON SCHEMA public TO backend_api;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO backend_api;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO backend_api;

    -- Grant privileges to Cron user
    GRANT CONNECT ON DATABASE domestic_postgres TO backend_cron;
    GRANT CREATE ON DATABASE domestic_postgres TO backend_cron;
    GRANT USAGE ON SCHEMA public TO backend_cron;
    GRANT CREATE ON SCHEMA public TO backend_cron;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO backend_cron;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO backend_cron;
