apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-keycloak-config
  namespace: domestic
  labels:
    app: postgres-keycloak
data:
  POSTGRES_DB: "domestic_keycloak"
  PGDATA: "/var/lib/postgresql/data/pgdata"
